/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables;

import com.epam.ta.reportportal.store.jooq.Indexes;
import com.epam.ta.reportportal.store.jooq.JPublic;
import com.epam.ta.reportportal.store.jooq.Keys;
import com.epam.ta.reportportal.store.jooq.tables.records.JIssueStatisticsIssueGroupRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIssueStatisticsIssueGroup extends TableImpl<JIssueStatisticsIssueGroupRecord> {

	private static final long serialVersionUID = 586087063;

	/**
	 * The reference instance of <code>public.issue_statistics_issue_group</code>
	 */
	public static final JIssueStatisticsIssueGroup ISSUE_STATISTICS_ISSUE_GROUP = new JIssueStatisticsIssueGroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<JIssueStatisticsIssueGroupRecord> getRecordType() {
		return JIssueStatisticsIssueGroupRecord.class;
	}

	/**
	 * The column <code>public.issue_statistics_issue_group.statistics_id</code>.
	 */
	public final TableField<JIssueStatisticsIssueGroupRecord, Long> STATISTICS_ID = createField(
			"statistics_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.issue_statistics_issue_group.issue_group_id</code>.
	 */
	public final TableField<JIssueStatisticsIssueGroupRecord, Short> ISSUE_GROUP_ID = createField(
			"issue_group_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>public.issue_statistics_issue_group.total</code>.
	 */
	public final TableField<JIssueStatisticsIssueGroupRecord, Integer> TOTAL = createField(
			"total", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this,
			""
	);

	/**
	 * Create a <code>public.issue_statistics_issue_group</code> table reference
	 */
	public JIssueStatisticsIssueGroup() {
		this(DSL.name("issue_statistics_issue_group"), null);
	}

	/**
	 * Create an aliased <code>public.issue_statistics_issue_group</code> table reference
	 */
	public JIssueStatisticsIssueGroup(String alias) {
		this(DSL.name(alias), ISSUE_STATISTICS_ISSUE_GROUP);
	}

	/**
	 * Create an aliased <code>public.issue_statistics_issue_group</code> table reference
	 */
	public JIssueStatisticsIssueGroup(Name alias) {
		this(alias, ISSUE_STATISTICS_ISSUE_GROUP);
	}

	private JIssueStatisticsIssueGroup(Name alias, Table<JIssueStatisticsIssueGroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private JIssueStatisticsIssueGroup(Name alias, Table<JIssueStatisticsIssueGroupRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return JPublic.PUBLIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<Index> getIndexes() {
		return Arrays.<Index>asList(Indexes.ISSUE_STATISTICS_ISSUE_GROUP_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<JIssueStatisticsIssueGroupRecord> getPrimaryKey() {
		return Keys.ISSUE_STATISTICS_ISSUE_GROUP_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<JIssueStatisticsIssueGroupRecord>> getKeys() {
		return Arrays.<UniqueKey<JIssueStatisticsIssueGroupRecord>>asList(Keys.ISSUE_STATISTICS_ISSUE_GROUP_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<JIssueStatisticsIssueGroupRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<JIssueStatisticsIssueGroupRecord, ?>>asList(
				Keys.ISSUE_STATISTICS_ISSUE_GROUP__ISSUE_STATISTICS_ISSUE_GROUP_STATISTICS_ID_FKEY,
				Keys.ISSUE_STATISTICS_ISSUE_GROUP__ISSUE_STATISTICS_ISSUE_GROUP_ISSUE_GROUP_ID_FKEY
		);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsIssueGroup as(String alias) {
		return new JIssueStatisticsIssueGroup(DSL.name(alias), this);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsIssueGroup as(Name alias) {
		return new JIssueStatisticsIssueGroup(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public JIssueStatisticsIssueGroup rename(String name) {
		return new JIssueStatisticsIssueGroup(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public JIssueStatisticsIssueGroup rename(Name name) {
		return new JIssueStatisticsIssueGroup(name, null);
	}
}
