/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.records;

import com.epam.ta.reportportal.store.jooq.tables.JExecutionStatistics;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JExecutionStatisticsRecord extends UpdatableRecordImpl<JExecutionStatisticsRecord>
		implements Record5<Long, Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = -2082319181;

	/**
	 * Setter for <code>public.execution_statistics.id</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.id</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.execution_statistics.passed</code>.
	 */
	public void setPassed(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.passed</code>.
	 */
	public Integer getPassed() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>public.execution_statistics.failed</code>.
	 */
	public void setFailed(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.failed</code>.
	 */
	public Integer getFailed() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>public.execution_statistics.skipped</code>.
	 */
	public void setSkipped(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.skipped</code>.
	 */
	public Integer getSkipped() {
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>public.execution_statistics.total</code>.
	 */
	public void setTotal(Integer value) {
		set(4, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.total</code>.
	 */
	public Integer getTotal() {
		return (Integer) get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Integer, Integer, Integer, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return JExecutionStatistics.EXECUTION_STATISTICS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return JExecutionStatistics.EXECUTION_STATISTICS.PASSED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return JExecutionStatistics.EXECUTION_STATISTICS.FAILED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return JExecutionStatistics.EXECUTION_STATISTICS.SKIPPED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return JExecutionStatistics.EXECUTION_STATISTICS.TOTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component2() {
		return getPassed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component3() {
		return getFailed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component4() {
		return getSkipped();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component5() {
		return getTotal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPassed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getFailed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getSkipped();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getTotal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value2(Integer value) {
		setPassed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value3(Integer value) {
		setFailed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value4(Integer value) {
		setSkipped(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value5(Integer value) {
		setTotal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord values(Long value1, Integer value2, Integer value3, Integer value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JExecutionStatisticsRecord
	 */
	public JExecutionStatisticsRecord() {
		super(JExecutionStatistics.EXECUTION_STATISTICS);
	}

	/**
	 * Create a detached, initialised JExecutionStatisticsRecord
	 */
	public JExecutionStatisticsRecord(Long id, Integer passed, Integer failed, Integer skipped, Integer total) {
		super(JExecutionStatistics.EXECUTION_STATISTICS);

		set(0, id);
		set(1, passed);
		set(2, failed);
		set(3, skipped);
		set(4, total);
	}
}
