/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.records;

import com.epam.ta.reportportal.store.jooq.tables.JIssueStatisticsIssueType;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIssueStatisticsIssueTypeRecord extends UpdatableRecordImpl<JIssueStatisticsIssueTypeRecord>
		implements Record3<Long, Long, Integer> {

	private static final long serialVersionUID = -464847411;

	/**
	 * Setter for <code>public.issue_statistics_issue_type.statistics_id</code>.
	 */
	public void setStatisticsId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>public.issue_statistics_issue_type.statistics_id</code>.
	 */
	public Long getStatisticsId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.issue_statistics_issue_type.issue_type_id</code>.
	 */
	public void setIssueTypeId(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>public.issue_statistics_issue_type.issue_type_id</code>.
	 */
	public Long getIssueTypeId() {
		return (Long) get(1);
	}

	/**
	 * Setter for <code>public.issue_statistics_issue_type.count</code>.
	 */
	public void setCount(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>public.issue_statistics_issue_type.count</code>.
	 */
	public Integer getCount() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return JIssueStatisticsIssueType.ISSUE_STATISTICS_ISSUE_TYPE.STATISTICS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return JIssueStatisticsIssueType.ISSUE_STATISTICS_ISSUE_TYPE.ISSUE_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return JIssueStatisticsIssueType.ISSUE_STATISTICS_ISSUE_TYPE.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component1() {
		return getStatisticsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component2() {
		return getIssueTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component3() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getStatisticsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getIssueTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsIssueTypeRecord value1(Long value) {
		setStatisticsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsIssueTypeRecord value2(Long value) {
		setIssueTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsIssueTypeRecord value3(Integer value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsIssueTypeRecord values(Long value1, Long value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JIssueStatisticsIssueTypeRecord
	 */
	public JIssueStatisticsIssueTypeRecord() {
		super(JIssueStatisticsIssueType.ISSUE_STATISTICS_ISSUE_TYPE);
	}

	/**
	 * Create a detached, initialised JIssueStatisticsIssueTypeRecord
	 */
	public JIssueStatisticsIssueTypeRecord(Long statisticsId, Long issueTypeId, Integer count) {
		super(JIssueStatisticsIssueType.ISSUE_STATISTICS_ISSUE_TYPE);

		set(0, statisticsId);
		set(1, issueTypeId);
		set(2, count);
	}
}
