/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.records;

import com.epam.ta.reportportal.store.jooq.tables.JIssueStatistics;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIssueStatisticsRecord extends UpdatableRecordImpl<JIssueStatisticsRecord> implements Record3<Long, Long, Long> {

	private static final long serialVersionUID = -1312210637;

	/**
	 * Setter for <code>public.issue_statistics.id</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>public.issue_statistics.id</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.issue_statistics.launch_id</code>.
	 */
	public void setLaunchId(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>public.issue_statistics.launch_id</code>.
	 */
	public Long getLaunchId() {
		return (Long) get(1);
	}

	/**
	 * Setter for <code>public.issue_statistics.test_item_id</code>.
	 */
	public void setTestItemId(Long value) {
		set(2, value);
	}

	/**
	 * Getter for <code>public.issue_statistics.test_item_id</code>.
	 */
	public Long getTestItemId() {
		return (Long) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Long> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Long> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return JIssueStatistics.ISSUE_STATISTICS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return JIssueStatistics.ISSUE_STATISTICS.LAUNCH_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return JIssueStatistics.ISSUE_STATISTICS.TEST_ITEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component2() {
		return getLaunchId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component3() {
		return getTestItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getLaunchId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getTestItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsRecord value2(Long value) {
		setLaunchId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsRecord value3(Long value) {
		setTestItemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JIssueStatisticsRecord values(Long value1, Long value2, Long value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JIssueStatisticsRecord
	 */
	public JIssueStatisticsRecord() {
		super(JIssueStatistics.ISSUE_STATISTICS);
	}

	/**
	 * Create a detached, initialised JIssueStatisticsRecord
	 */
	public JIssueStatisticsRecord(Long id, Long launchId, Long testItemId) {
		super(JIssueStatistics.ISSUE_STATISTICS);

		set(0, id);
		set(1, launchId);
		set(2, testItemId);
	}
}
