/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.records;

import com.epam.ta.reportportal.store.jooq.enums.JStatusEnum;
import com.epam.ta.reportportal.store.jooq.tables.JTestItemResults;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JTestItemResultsRecord extends UpdatableRecordImpl<JTestItemResultsRecord>
		implements Record5<Long, JStatusEnum, Timestamp, Double, Long> {

	private static final long serialVersionUID = -1319331617;

    /**
     * Setter for <code>public.test_item_results.item_id</code>.
     */
    public void setItemId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.test_item_results.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.test_item_results.status</code>.
     */
    public void setStatus(JStatusEnum value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.test_item_results.status</code>.
     */
    public JStatusEnum getStatus() {
        return (JStatusEnum) get(1);
    }

    /**
     * Setter for <code>public.test_item_results.end_time</code>.
     */
    public void setEndTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.test_item_results.end_time</code>.
     */
    public Timestamp getEndTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.test_item_results.duration</code>.
     */
    public void setDuration(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.test_item_results.duration</code>.
     */
    public Double getDuration() {
        return (Double) get(3);
    }

	/**
	 * Setter for <code>public.test_item_results.execution_statistics</code>.
	 */
	public void setExecutionStatistics(Long value) {
		set(4, value);
	}

	/**
	 * Getter for <code>public.test_item_results.execution_statistics</code>.
	 */
	public Long getExecutionStatistics() {
		return (Long) get(4);
	}

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
	public Row5<Long, JStatusEnum, Timestamp, Double, Long> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

    /**
     * {@inheritDoc}
     */
    @Override
	public Row5<Long, JStatusEnum, Timestamp, Double, Long> valuesRow() {
		return (Row5) super.valuesRow();
	}

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JTestItemResults.TEST_ITEM_RESULTS.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JStatusEnum> field2() {
        return JTestItemResults.TEST_ITEM_RESULTS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return JTestItemResults.TEST_ITEM_RESULTS.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return JTestItemResults.TEST_ITEM_RESULTS.DURATION;
    }

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return JTestItemResults.TEST_ITEM_RESULTS.EXECUTION_STATISTICS;
	}

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JStatusEnum component2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getDuration();
    }

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component5() {
		return getExecutionStatistics();
	}

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JStatusEnum value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getDuration();
    }

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getExecutionStatistics();
	}

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemResultsRecord value1(Long value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemResultsRecord value2(JStatusEnum value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemResultsRecord value3(Timestamp value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemResultsRecord value4(Double value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public JTestItemResultsRecord value5(Long value) {
		setExecutionStatistics(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JTestItemResultsRecord values(Long value1, JStatusEnum value2, Timestamp value3, Double value4, Long value5) {
		value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
		value5(value5);
		return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTestItemResultsRecord
     */
    public JTestItemResultsRecord() {
        super(JTestItemResults.TEST_ITEM_RESULTS);
    }

    /**
     * Create a detached, initialised JTestItemResultsRecord
     */
	public JTestItemResultsRecord(Long itemId, JStatusEnum status, Timestamp endTime, Double duration, Long executionStatistics) {
		super(JTestItemResults.TEST_ITEM_RESULTS);

        set(0, itemId);
        set(1, status);
        set(2, endTime);
        set(3, duration);
		set(4, executionStatistics);
	}
}
